name: CI/CD pipeline for Flask App

on:
  push:
    branches: [ main ]
    pull_request:
      branches: [ main ]

env:
  IMAGE_NAME: aashishsharma5555/flaskapp

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOKER_PASSWORD }}

      - name: Build Docker Image
        run: docker-compose

      - name: Run Containers
        run: docker-compose up -d

      - name: Wait for MySql service
        run: sleep 30

      - name: Tear Down Containners
        run: docker-compose down


